---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_version: '7.4'

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: shaneholloman.remi
      when: ansible_os_family == 'RedHat'
    - role: shaneholloman.phps
    - role: shaneholloman.php

  post_tasks:
    - name: Confirm PHP version is correct.
      ansible.builtin.shell: php -v | grep -F '{{ php_version }}'
      changed_when: false
